name: Production Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    #- name: Update apt-get
    #  run: sudo apt-get update -y

    - name: Install expect
      run: sudo apt-get install -qq expect

    - name: Deploy to server
      run: sh ./build/deploy/production.sh ${{ secrets.SSH_PROD_USER }} ${{ secrets.SSH_PROD_PASS }} ${{ secrets.GIT_USER }} ${{ secrets.GIT_PASS }}